services:
  app:
    build: .
    container_name: thanh_giuse_pc_app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:7-alpine
    container_name: thanh_giuse_pc_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: thanh_giuse_pc_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
